version: '3.8'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /srv/docker/influxdb/data:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    ports: 
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: